# -*- coding: utf-8 -*-
"""Parity fixture for the Dart metric channel (ADR 0557/0558).

The Dart unit and the Python measurement must be the SAME function, or the shipped
rule is not the measured rule (LESSONS L662). This writes the rows Dart has to
reproduce exactly: real held-out GuitarSet onset phases with their prescribed slot and
direction, plus the synthetic edge cases a real corpus never lands on (a phase exactly
on a slot boundary, the wrap at 1.0, a rest slot, a pattern whose length is not a
multiple of the beat count).

    GUITARSET_DIR=/path/to/guitarset python ml/make_metric_channel_fixture.py

Writes `test/fixtures/strum_metric_channel_parity.json`. Annotation only - no audio,
no model, no TensorFlow.
"""
from __future__ import annotations

import json
import os

import numpy as np

import probe_direction_metric as M

# Patterns as the Dart side sees them: one bar of slots, "d" / "u" / null for a rest.
# The first is GuitarSet's implied lesson expressed over a 4/4 bar (sixteenths); the
# rest are real presets from `lib/features/songs/theory/strum_patterns.dart`, so the
# fixture covers the subdivisions the app actually ships.
PATTERNS = {
    "sixteenth-alternating": (["d", "u"] * 8, 4),
    "Eighths": (["d", "u"] * 4, 4),
    "Down": (["d", None] * 4, 4),
    "Folk": (["d", None, "d", "u", None, "u", "d", "u"], 4),
    "Reggae": ([None, "u"] * 4, 4),
    "Waltz": (["d", None, "d", None, "d", None], 3),
}


def slot_of(phase_in_bar: float, length: int):
    """The Dart rule, restated here so the fixture is generated by the SAME arithmetic
    the probe measures with: nearest slot, wrapping."""
    scaled = phase_in_bar * length
    index = int(np.floor(scaled + 0.5)) % length
    offset = scaled - np.floor(scaled + 0.5)
    return index, float(offset)


def rows_for(phase_in_bar: float, name: str):
    pattern, beats = PATTERNS[name]
    index, offset = slot_of(phase_in_bar, len(pattern))
    return {
        "pattern": name,
        "slots": pattern,
        "beatsPerBar": beats,
        "phaseInBar": float(phase_in_bar),
        "expectedSlot": index,
        "expectedDirection": pattern[index],
        "expectedOffsetSlots": offset,
    }


def main():
    cases = []

    # 1. Real held-out onsets. The probe gives phase within the BEAT; GuitarSet's takes
    #    are 4/4, so the bar phase of a beat-phase p on beat b is (b - 1 + p) / 4. Beat
    #    1 is used here because the sixteenth-alternating pattern repeats every beat, so
    #    the bar position cannot change the answer - and that invariance is itself worth
    #    pinning, which case group 3 does.
    rows = M.collect()
    _train, test = M.splits(rows)
    for row in test[:120]:
        cases.append(rows_for(row["phase"] / 4.0, "sixteenth-alternating"))

    # 2. Synthetic edge cases no corpus lands on exactly.
    for name in PATTERNS:
        length = len(PATTERNS[name][0])
        for phase in (0.0, 0.5 / length, 1.0 / length, 1.5 / length,
                      0.5, 1.0 - 1e-12, 0.999999):
            cases.append(rows_for(phase, name))

    # 3. The wrap and the sign: a phase just below 1.0 must land on slot 0, not on
    #    `length`, and a NEGATIVE phase (an onset before the bar start, which the
    #    pipeline can produce when the bar is re-anchored) must wrap the same way.
    for name in PATTERNS:
        length = len(PATTERNS[name][0])
        for phase in (1.0 - 0.4 / length, -0.25 / length, -1.0 + 0.25 / length):
            wrapped = phase % 1.0
            case = rows_for(wrapped, name)
            case["phaseInBar"] = float(phase)  # Dart must wrap this itself
            cases.append(case)

    out = {
        "note": "E18-R35. The metric channel (ADR 0557 D3, ADR 0558): the prescribed "
                "pattern's direction at the NEAREST slot, wrapping. Dart must reproduce "
                "expectedSlot and expectedDirection EXACTLY and expectedOffsetSlots to "
                "1e-9. Generated by ml/make_metric_channel_fixture.py from the same "
                "arithmetic probe_direction_metric.slot_call measures with - if these "
                "two ever disagree, the shipped rule is not the measured rule (L662).",
        "rule": "slot = floor(phaseInBar * slots + 0.5) mod slots; direction = "
                "pattern[slot]; a null slot is a REST, which means the channel has NO "
                "OPINION (distinct from the channel being UNAVAILABLE, which is what a "
                "missing tempo grid produces).",
        "cases": cases,
    }
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "test", "fixtures", "strum_metric_channel_parity.json")
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(out, handle, indent=2)
        handle.write("\n")
    print("wrote %s (%d cases)" % (path, len(cases)))


if __name__ == "__main__":
    main()
