# -*- coding: utf-8 -*-
"""Parity fixture for the Dart metric channel (ADR 0557/0558/0560).

The Dart unit and the Python measurement must be the SAME function, or the shipped
rule is not the measured rule (LESSONS L662/L673). This writes the rows Dart has to
reproduce exactly: real held-out GuitarSet onset phases with their prescribed crossing
and direction, plus the synthetic edge cases a real corpus never lands on (a phase
exactly on a crossing boundary, the wrap at 1.0, a negative phase, a ghost crossing, a
3/4 authored pattern).

Every crossing carries BOTH a direction and whether the pattern asks for a sound there.
A silent crossing is not a crossing without a direction: the strumming hand is a
pendulum and does not stop, so it still travels through -- `RhythmGrid`'s
`StrokeSound.ghost`, from the same pedagogy sources. The first version of this fixture
encoded a rest as "no direction", which was wrong.

Note the measurement is unaffected by that correction: GuitarSet's implied pattern is a
strict sixteenth alternation with NO ghost crossings, so `slot_call`'s answer never
depended on the rest semantics.

    GUITARSET_DIR=/path/to/guitarset python ml/make_metric_channel_fixture.py

Writes `test/fixtures/strum_metric_channel_parity.json`. Annotation only - no audio,
no model, no TensorFlow.
"""
from __future__ import annotations

import json
import os

import numpy as np

import probe_direction_metric as M

D, U = "d", "u"


def pendulum(beats, struck):
    """Eighth-resolution crossings with directions DERIVED from position: even
    crossings are downstrokes, odd ones upstrokes. Mirrors
    `RhythmGrid.pendulumDirection` for `RhythmSubdivision.eighth`; it is restated here
    only to generate the fixture, and `RhythmGrid` stays the single authority in the
    app."""
    assert len(struck) == beats * 2, (beats, len(struck))
    return [{"dir": D if i % 2 == 0 else U, "expected": bool(s)}
            for i, s in enumerate(struck)]


# Patterns as the Dart side sees them: one bar of CROSSINGS.
PATTERNS = {
    # GuitarSet's implied lesson over a 4/4 bar: sixteenth alternation, every
    # crossing struck. This is the pattern every number in ADR 0557/0558 was
    # measured under.
    "sixteenth-alternating": (
        [{"dir": D if i % 2 == 0 else U, "expected": True} for i in range(16)], 4),
    # Real presets from `lib/features/songs/theory/strum_patterns.dart`.
    "Eighths": (pendulum(4, [True] * 8), 4),
    # The QUARTER-note preset, expanded to crossings: the hand comes back UP between
    # the beats, and those returns are ghosts. Read at slot resolution instead, a
    # stroke between beats would be called DOWN while the hand travelled UP.
    "Down-expanded": (pendulum(4, [True, False] * 4), 4),
    "Folk": (pendulum(4, [True, False, True, True, False, True, True, True]), 4),
    "Reggae": (pendulum(4, [False, True] * 4), 4),
    # 3/4 AUTHORED oom-pah: bass down on ONE, light chords UP on two and three. The
    # taught counterexample to the pendulum (`RhythmGrid.authored`), so crossing 2 is
    # an UP although its position would derive DOWN. Ghost crossings keep the
    # pendulum's direction, because unstruck travel is hand motion, not notation.
    "Waltz-oom-pah": ([
        {"dir": D, "expected": True},
        {"dir": U, "expected": False},
        {"dir": U, "expected": True},
        {"dir": U, "expected": False},
        {"dir": U, "expected": True},
        {"dir": U, "expected": False},
    ], 3),
}


def crossing_of(phase_in_bar, length):
    """The Dart rule, restated here so the fixture is generated by the SAME arithmetic
    the probe measures with: nearest crossing, wrapping."""
    scaled = phase_in_bar * length
    index = int(np.floor(scaled + 0.5)) % length
    offset = scaled - np.floor(scaled + 0.5)
    return index, float(offset)


def case_for(phase_in_bar, name):
    slots, beats = PATTERNS[name]
    index, offset = crossing_of(phase_in_bar, len(slots))
    return {
        "pattern": name,
        "slots": slots,
        "beatsPerBar": beats,
        "phaseInBar": float(phase_in_bar),
        "expectedSlot": index,
        "expectedDirection": slots[index]["dir"],
        "expectedHere": slots[index]["expected"],
        "expectedOffsetSlots": offset,
    }


def main():
    cases = []

    # 1. Real held-out onsets. The probe gives phase within the BEAT; GuitarSet's
    #    takes are 4/4, so beat 1's bar phase is p / 4. The sixteenth-alternating
    #    pattern repeats every beat, so the bar position cannot change the answer --
    #    and case group 3 pins that invariance directly.
    rows = M.collect()
    _train, test = M.splits(rows)
    for row in test[:120]:
        cases.append(case_for(row["phase"] / 4.0, "sixteenth-alternating"))

    # 2. Synthetic edge cases no corpus lands on exactly.
    for name, (slots, _beats) in PATTERNS.items():
        length = len(slots)
        for phase in (0.0, 0.5 / length, 1.0 / length, 1.5 / length,
                      0.5, 1.0 - 1e-12, 0.999999):
            cases.append(case_for(phase, name))

    # 3. The wrap and the sign: a phase just below 1.0 must land on crossing 0, not
    #    on `length`, and a NEGATIVE phase (an onset before the bar start, which a
    #    stroke arriving early produces) must wrap the same way.
    for name, (slots, _beats) in PATTERNS.items():
        length = len(slots)
        for phase in (1.0 - 0.4 / length, -0.25 / length, -1.0 + 0.25 / length):
            case = case_for(phase % 1.0, name)
            case["phaseInBar"] = float(phase)  # Dart must wrap this itself
            cases.append(case)

    out = {
        "note": "E18-R38. The metric channel (ADR 0557 D3, 0558, 0560): the prescribed "
                "pattern's direction at the NEAREST CROSSING, wrapping. Dart must "
                "reproduce expectedSlot, expectedDirection and expectedHere EXACTLY and "
                "expectedOffsetSlots to 1e-9. Generated by "
                "ml/make_metric_channel_fixture.py from the same arithmetic "
                "probe_direction_metric.slot_call measures with - if these two ever "
                "disagree, the shipped rule is not the measured rule (L662/L673).",
        "rule": "slot = floor(phaseInBar * crossings + 0.5) mod crossings; direction = "
                "pattern[slot].dir, which is ALWAYS defined because the pendulum never "
                "stops; expectedHere = pattern[slot].expected, false on a GHOST crossing "
                "(real hand travel, nothing the pattern asked for). A missing tempo grid "
                "is a different state again: UNAVAILABLE.",
        "cases": cases,
    }
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "test", "fixtures", "strum_metric_channel_parity.json")
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(out, handle, indent=2)
        handle.write("\n")
    print("wrote %s (%d cases)" % (path, len(cases)))


if __name__ == "__main__":
    main()
