/// Public domain contract for cross-feature Practice Generator consumers.
library;

export 'application/port/skill_snapshot_reader.dart';
export 'application/port/practice_catalog_reader.dart';
export 'application/port/analysis_evidence_reader.dart';
export 'application/port/vision_evidence_reader.dart';
export 'application/port/planner_assist_gateway.dart';
export 'application/controller/plan_generator_controller.dart';
export 'application/controller/active_plan_controller.dart';
export 'application/controller/today_plan_controller.dart';
export 'application/model/generation_state.dart';
export 'application/service/evidence_aggregator.dart';
export 'application/service/generation_orchestrator.dart';
export 'application/service/skill_estimate_reducer.dart';
export 'application/service/plan_execution_coordinator.dart';
export 'application/service/outcome_ingestion_service.dart';
export 'application/usecase/record_practice_outcome.dart';
export 'application/usecase/revise_practice_plan.dart';
export 'application/usecase/pause_practice_plan.dart';
export 'application/usecase/resume_practice_plan.dart';
export 'application/usecase/delete_practice_planning_data.dart';
export 'application/usecase/export_practice_planning_data.dart';
export 'application/usecase/start_plan_generation.dart';

export 'data/adapter/legacy_lesson_candidate_adapter.dart';
export 'data/adapter/legacy_lesson_catalog_adapter.dart';
export 'data/adapter/legacy_mapping_table.dart';
export 'data/adapter/legacy_progress_evidence_adapter.dart';
export 'data/adapter/practice_outcome_adapter.dart';
export 'data/adapter/analysis_evidence_adapter.dart';
export 'data/adapter/vision_evidence_adapter.dart';
export 'data/adapter/tutor_plan_proposal_adapter.dart';
export 'data/adapter/practice_engine_catalog_adapter.dart';
export 'data/adapter/song_goal_reader_adapter.dart';
export 'data/ai/planner_assist_schema.dart';
export 'data/ai/remote_planner_assist_gateway.dart';
export 'data/ai/fake_planner_assist_gateway.dart';
export 'data/local/local_practice_evidence_repository.dart';
export 'data/local/local_practice_plan_repository.dart';
export 'data/local/practice_plan_migrator.dart';
// The older serializer record is repository-local. R23 publishes the richer
// execution [PracticeOutcome] instead; local persistence keeps importing its
// own record type directly.
export 'data/local/practice_plan_serializer.dart' hide PracticeOutcome;

export 'domain/id/planner_ids.dart';
export 'domain/model/exercise_candidate.dart';
export 'domain/model/exercise_prescription.dart';
export 'domain/model/learner_constraints.dart';
export 'domain/model/adaptive_practice_plan.dart';
export 'domain/model/adaptation_decision.dart';
export 'domain/model/candidate_decision.dart';
export 'domain/model/plan_enums.dart';
export 'domain/model/plan_change_set.dart';
export 'domain/model/plan_revision.dart';
export 'domain/model/plan_validation_issue.dart';
export 'domain/model/practice_block.dart';
export 'domain/model/practice_day.dart';
export 'domain/model/practice_generation_request.dart';
export 'domain/model/practice_catalog_snapshot.dart';
export 'domain/model/practice_goal.dart';
export 'domain/model/progression_rule.dart';
export 'domain/model/review_item.dart';
export 'domain/model/schedule_decision.dart';
export 'domain/model/skill_evidence.dart';
export 'domain/model/skill_estimate.dart';
export 'domain/model/skill_priority.dart';
export 'domain/model/success_criteria.dart';
export 'domain/model/time_budget.dart';
export 'domain/model/weekly_availability.dart';
export 'domain/policy/candidate_policy.dart';
export 'domain/policy/evidence_weight_policy.dart';
export 'domain/policy/missed_day_policy.dart';
export 'domain/policy/priority_policy.dart';
export 'domain/policy/progression_policy.dart';
export 'domain/policy/scheduling_policy.dart';
export 'domain/policy/spaced_repetition_policy.dart';
export 'domain/policy/time_allocation_policy.dart';
export 'domain/repository/practice_evidence_repository.dart';
export 'domain/service/candidate_selector.dart';
export 'domain/service/adaptation_decider.dart';
export 'domain/service/plan_repairer.dart';
export 'domain/service/plan_validator.dart';
export 'domain/service/plan_compiler.dart';
export 'domain/service/priority_engine.dart';
export 'domain/service/request_validator.dart';
export 'domain/service/review_queue.dart';
export 'domain/service/time_budget_allocator.dart';
export 'domain/service/weekly_scheduler.dart';
export 'domain/service/song_block_compiler.dart';
export 'domain/service/song_goal_planner.dart';

export 'presentation/controller/plan_setup_controller.dart';
export 'presentation/controller/plan_preview_controller.dart';
export 'presentation/providers/practice_generator_providers.dart';
export 'presentation/screens/plan_setup_screen.dart';
export 'presentation/screens/plan_preview_screen.dart';
export 'presentation/screens/today_plan_screen.dart';
export 'presentation/screens/weekly_plan_screen.dart';
export 'presentation/screens/plan_change_review_screen.dart';
export 'presentation/screens/plan_privacy_screen.dart';
export 'presentation/widgets/plan_block_card.dart';
export 'presentation/widgets/plan_day_card.dart';
export 'presentation/widgets/plan_reason_sheet.dart';
export 'presentation/widgets/catch_up_sheet.dart';
