import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:music_theory/features/live/engine/dsp/log_mel_extractor.dart';

/// PARITY gate for the ML front-end (docs/plans/ml-track.md P0.1, chunk 018).
///
/// The Dart log-mel MUST reproduce ml/features.py `log_mel` on identical PCM —
/// a drifted front-end silently destroys any model trained on those features.
/// The fixture is generated by `python3 ml/make_logmel_fixture.py` and is the
/// contract between the two implementations.
void main() {
  final fixture = json.decode(
    File('test/fixtures/logmel_parity.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  group('LogMelExtractor parity with ml/features.py', () {
    test('fixture matches the chunk-018 feature spec', () {
      expect(fixture['sr'], 16000);
      expect(fixture['n_fft'], 2048);
      expect(fixture['hop'], 160);
      expect(fixture['n_mels'], 128);
      expect(fixture['fmin'], 30.0);
    });

    test('log-mel frames match the Python reference within 1e-3', () {
      final pcm = Float64List.fromList(
        (fixture['pcm'] as List).cast<num>().map((v) => v.toDouble()).toList(),
      );
      final expected = (fixture['logmel'] as List)
          .map((row) =>
              (row as List).cast<num>().map((v) => v.toDouble()).toList())
          .toList();

      final extractor = LogMelExtractor(sampleRate: fixture['sr'] as int);
      final frames = extractor.process(pcm);

      expect(frames.length, expected.length,
          reason: 'frame count must match 1 + (n - nFft) ~/ hop');
      var maxErr = 0.0;
      for (var i = 0; i < frames.length; i++) {
        expect(frames[i].length, 128);
        for (var m = 0; m < 128; m++) {
          final err = (frames[i][m] - expected[i][m]).abs();
          if (err > maxErr) maxErr = err;
        }
      }
      expect(maxErr, lessThan(1e-3),
          reason: 'max |dart - python| across all frames/mels');
    });

    test('shorter-than-one-window input yields no frames', () {
      final extractor = LogMelExtractor(sampleRate: 16000);
      expect(extractor.process(Float64List(2047)), isEmpty);
    });

    test('silence maps every mel bin to log(1e-6)', () {
      final extractor = LogMelExtractor(sampleRate: 16000);
      final frames = extractor.process(Float64List(2048));
      expect(frames, hasLength(1));
      for (final v in frames.single) {
        expect(v, closeTo(-13.815510557964274, 1e-9)); // ln(1e-6)
      }
    });
  });
}
