import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';
import 'package:strumsight/core/music/strum.dart';
import 'package:strumsight/features/curriculum/domain/rhythm_grid.dart';
import 'package:strumsight/features/live/engine/dsp/strum_metric_channel.dart';

StrumDirection? _dir(Object? raw) => switch (raw) {
  'd' => StrumDirection.down,
  'u' => StrumDirection.up,
  _ => null,
};

/// The metric channel (ADR 0557/0558/0560). Four groups, matching AGENTS.md §9's
/// demands for a measurement-backed change: PARITY against the fixture the Python
/// probe generated, the STATE contract (the outcomes must stay distinguishable),
/// the CROSSING expansion (where reading a quarter grid wrongly would invert
/// answers), and randomized PROPERTIES over the geometry.
void main() {
  group('parity with the measured rule (fixture)', () {
    // If these ever disagree, the shipped rule is not the rule the 0.9797 was
    // measured under, and every number quoted for this channel is void
    // (`docs/LESSONS.md` L662, L673). Regenerated by
    // `ml/make_metric_channel_fixture.py`.
    final file = File('test/fixtures/strum_metric_channel_parity.json');

    test('fixture exists', () {
      expect(
        file.existsSync(),
        isTrue,
        reason: 'run ml/make_metric_channel_fixture.py',
      );
    });

    test(
      'every case reproduces crossing, direction, expectation and offset',
      () {
        final fixture =
            jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
        final cases = (fixture['cases'] as List).cast<Map<String, Object?>>();
        expect(cases, isNotEmpty);

        for (final (index, row) in cases.indexed) {
          final channel = StrumMetricChannel(
            pattern: [
              for (final slot
                  in (row['slots'] as List).cast<Map<String, Object?>>())
                MetricSlot(
                  direction: _dir(slot['dir'])!,
                  expected: slot['expected']! as bool,
                ),
            ],
            beatsPerBar: row['beatsPerBar']! as int,
          );
          // The fixture stores a bar PHASE; turn it back into a time against a
          // fixed tempo so the unit is exercised through its real entry point
          // rather than through an internal shortcut.
          const bpm = 120.0;
          final barSec = channel.beatsPerBar * 60.0 / bpm;
          final phase = (row['phaseInBar']! as num).toDouble();
          final call = channel.callAt(
            onsetTimeSec: 7.5 + phase * barSec,
            barStartSec: 7.5,
            bpm: bpm,
          );
          final where = 'case $index (${row['pattern']}, phase $phase)';
          expect(call.slot, row['expectedSlot'], reason: 'slot, $where');
          expect(
            call.direction,
            _dir(row['expectedDirection']),
            reason: 'direction, $where',
          );
          expect(
            call.expectedHere,
            row['expectedHere'],
            reason: 'expectedHere, $where',
          );
          expect(
            call.offsetSlots,
            closeTo((row['expectedOffsetSlots']! as num).toDouble(), 1e-9),
            reason: 'offset, $where',
          );
        }
      },
    );
  });

  group('the states stay distinguishable', () {
    // "No grid" and "the pattern ghosts this crossing" both mean the fusion must
    // lean on the acoustic channel, but they are different diagnostics and only
    // one is a pattern violation worth telling the learner about (ADR 0556 D4).
    const eighths = StrumMetricChannel(
      pattern: [
        MetricSlot(direction: StrumDirection.down, expected: true),
        MetricSlot(direction: StrumDirection.up, expected: true),
        MetricSlot(direction: StrumDirection.down, expected: true),
        MetricSlot(direction: StrumDirection.up, expected: true),
        MetricSlot(direction: StrumDirection.down, expected: true),
        MetricSlot(direction: StrumDirection.up, expected: true),
        MetricSlot(direction: StrumDirection.down, expected: true),
        MetricSlot(direction: StrumDirection.up, expected: true),
      ],
      beatsPerBar: 4,
    );
    const quartersExpanded = StrumMetricChannel(
      pattern: [
        MetricSlot(direction: StrumDirection.down, expected: true),
        MetricSlot(direction: StrumDirection.up, expected: false),
        MetricSlot(direction: StrumDirection.down, expected: true),
        MetricSlot(direction: StrumDirection.up, expected: false),
        MetricSlot(direction: StrumDirection.down, expected: true),
        MetricSlot(direction: StrumDirection.up, expected: false),
        MetricSlot(direction: StrumDirection.down, expected: true),
        MetricSlot(direction: StrumDirection.up, expected: false),
      ],
      beatsPerBar: 4,
    );

    test('no tempo grid is UNAVAILABLE, not a guess', () {
      for (final bpm in [0.0, -1.0, double.nan, double.infinity]) {
        final call = eighths.callAt(
          onsetTimeSec: 1.0,
          barStartSec: 0.0,
          bpm: bpm,
        );
        expect(call.available, isFalse, reason: 'bpm $bpm');
        expect(call.hasOpinion, isFalse, reason: 'bpm $bpm');
        expect(call.direction, isNull, reason: 'bpm $bpm');
        expect(call.slot, -1, reason: 'bpm $bpm');
      }
    });

    test('a non-finite time is UNAVAILABLE rather than a wrapped NaN slot', () {
      expect(
        eighths
            .callAt(onsetTimeSec: double.nan, barStartSec: 0, bpm: 120)
            .available,
        isFalse,
      );
      expect(
        eighths
            .callAt(onsetTimeSec: 1, barStartSec: double.infinity, bpm: 120)
            .available,
        isFalse,
      );
    });

    test('a GHOST crossing still carries a direction', () {
      // The correction this file's first version needed. The hand is a pendulum
      // and does not stop, so a crossing the pattern leaves silent is real hand
      // travel with a real direction — and a learner who strikes there has their
      // direction predicted anyway. 120 bpm, 4/4: a bar is 2 s, an eighth 0.25 s,
      // and crossing 1 is the ghosted return.
      final call = quartersExpanded.callAt(
        onsetTimeSec: 0.25,
        barStartSec: 0.0,
        bpm: 120,
      );
      expect(call.slot, 1);
      expect(call.available, isTrue);
      expect(call.direction, StrumDirection.up);
      expect(call.hasOpinion, isTrue, reason: 'a ghost is not an absence');
      expect(
        call.expectedHere,
        isFalse,
        reason: 'the pattern asked for nothing here',
      );
    });

    test('a struck crossing names its direction and is expected', () {
      final call = quartersExpanded.callAt(
        onsetTimeSec: 0.5,
        barStartSec: 0.0,
        bpm: 120,
      );
      expect(call.slot, 2);
      expect(call.direction, StrumDirection.down);
      expect(call.expectedHere, isTrue);
    });

    test('slotsPerBeat reports the crossing resolution', () {
      expect(eighths.slotsPerBeat, 2.0);
      const sixteenths = StrumMetricChannel(
        pattern: [
          MetricSlot(direction: StrumDirection.down, expected: true),
          MetricSlot(direction: StrumDirection.up, expected: true),
          MetricSlot(direction: StrumDirection.down, expected: true),
          MetricSlot(direction: StrumDirection.up, expected: true),
        ],
        beatsPerBar: 1,
      );
      expect(sixteenths.slotsPerBeat, 4.0);
    });
  });

  group('crossings(): a QUARTER grid must be expanded, or answers invert', () {
    test('an eighth grid is taken as notated', () {
      final grid = RhythmGrid.pendulum(
        subdivision: RhythmSubdivision.eighth,
        struck: const [true, false, true, true, false, true, true, true],
      );
      final channel = StrumMetricChannel.crossings(
        directions: [for (final slot in grid.slots) slot.direction],
        struck: [for (final slot in grid.slots) slot.isStruck],
        slotsPerBeatNotated: grid.subdivision.slotsPerBeat,
        beatsPerBar: grid.beatsPerBar,
      );
      expect(channel.pattern, hasLength(8));
      expect(channel.slotsPerBeat, 2.0);
      for (var i = 0; i < 8; i++) {
        expect(channel.pattern[i].direction, grid.slots[i].direction);
        expect(channel.pattern[i].expected, grid.slots[i].isStruck);
      }
    });

    test('a quarter grid becomes eight crossings, alternating', () {
      final grid = RhythmGrid.pendulum(
        subdivision: RhythmSubdivision.quarter,
        struck: const [true, true, true, true],
      );
      expect(grid.slots, hasLength(4), reason: 'four NOTATED slots');
      final channel = StrumMetricChannel.crossings(
        directions: [for (final slot in grid.slots) slot.direction],
        struck: [for (final slot in grid.slots) slot.isStruck],
        slotsPerBeatNotated: grid.subdivision.slotsPerBeat,
        beatsPerBar: grid.beatsPerBar,
      );
      expect(channel.pattern, hasLength(8), reason: 'eight CROSSINGS');
      // The expansion must agree with RhythmGrid's own account of what the hand
      // does, which is the single authority for that (no second derivation).
      expect([
        for (final slot in channel.pattern) slot.expected,
      ], grid.handCrossings);
      for (var i = 0; i < 8; i++) {
        expect(
          channel.pattern[i].direction,
          i.isEven ? StrumDirection.down : StrumDirection.up,
        );
      }
    });

    test('without the expansion, an off-beat stroke would be called DOWN', () {
      // The defect in numbers. A stroke halfway between two beats: read at
      // CROSSING resolution the hand is travelling UP, which is the truth; read at
      // the quarter grid's own four-slot resolution it lands on the nearest beat
      // and reads DOWN. That is a confident inversion on exactly the off-beat
      // strokes a learner adds when they start filling a pattern in.
      final grid = RhythmGrid.pendulum(
        subdivision: RhythmSubdivision.quarter,
        struck: const [true, true, true, true],
      );
      final expanded = StrumMetricChannel.crossings(
        directions: [for (final slot in grid.slots) slot.direction],
        struck: [for (final slot in grid.slots) slot.isStruck],
        slotsPerBeatNotated: grid.subdivision.slotsPerBeat,
      );
      final unexpanded = StrumMetricChannel(
        beatsPerBar: 4,
        pattern: [
          for (final slot in grid.slots)
            MetricSlot(direction: slot.direction, expected: slot.isStruck),
        ],
      );
      // 120 bpm: beat = 0.5 s, so 0.25 s is the "&" of beat 1.
      const at = 0.25;
      expect(
        expanded.callAt(onsetTimeSec: at, barStartSec: 0, bpm: 120).direction,
        StrumDirection.up,
      );
      expect(
        unexpanded.callAt(onsetTimeSec: at, barStartSec: 0, bpm: 120).direction,
        StrumDirection.down,
        reason: 'this is the inversion the expansion exists to prevent',
      );
    });

    test('an AUTHORED grid keeps its authored directions', () {
      // The taught 3/4 oom-pah: bass DOWN on one, light chords UP on two and
      // three. `followsPendulum` is false, and the channel must not "correct" it —
      // a model that called that wrong would teach something false about a pattern
      // real teachers teach.
      final grid = RhythmGrid.authored(
        subdivision: RhythmSubdivision.eighth,
        beatsPerBar: 3,
        strokes: const [
          StrumDirection.down,
          null,
          StrumDirection.up,
          null,
          StrumDirection.up,
          null,
        ],
      );
      expect(grid.followsPendulum, isFalse);
      final channel = StrumMetricChannel.crossings(
        directions: [for (final slot in grid.slots) slot.direction],
        struck: [for (final slot in grid.slots) slot.isStruck],
        slotsPerBeatNotated: grid.subdivision.slotsPerBeat,
        beatsPerBar: grid.beatsPerBar,
      );
      expect(channel.pattern[2].direction, StrumDirection.up);
      expect(channel.pattern[2].expected, isTrue);
      // 120 bpm, 3/4: a bar is 1.5 s, an eighth 0.25 s, so crossing 2 is at 0.5 s.
      final call = channel.callAt(onsetTimeSec: 0.5, barStartSec: 0, bpm: 120);
      expect(call.slot, 2);
      expect(call.direction, StrumDirection.up);
    });
  });

  group('properties (randomized)', () {
    // Sixteenth alternation over a 4/4 bar: GuitarSet's implied lesson, and the
    // pattern every number in ADR 0557/0558 was measured under.
    final sixteenths = StrumMetricChannel(
      pattern: [
        for (var i = 0; i < 16; i++)
          MetricSlot(
            direction: i.isEven ? StrumDirection.down : StrumDirection.up,
            expected: true,
          ),
      ],
      beatsPerBar: 4,
    );

    test('an onset dead on a crossing centre lands on that crossing', () {
      final random = math.Random(20260912);
      for (var trial = 0; trial < 400; trial++) {
        final bpm = 60 + random.nextDouble() * 140; // the TempoTracker's range
        final barStart = random.nextDouble() * 30;
        final slot = random.nextInt(16);
        final barSec = 4 * 60.0 / bpm;
        final call = sixteenths.callAt(
          onsetTimeSec: barStart + slot / 16 * barSec,
          barStartSec: barStart,
          bpm: bpm,
        );
        expect(call.slot, slot, reason: 'bpm $bpm slot $slot');
        expect(call.offsetSlots.abs(), lessThan(1e-9));
        expect(
          call.direction,
          slot.isEven ? StrumDirection.down : StrumDirection.up,
        );
      }
    });

    test('offsetSlots always lies within [-0.5, 0.5]', () {
      final random = math.Random(7);
      for (var trial = 0; trial < 2000; trial++) {
        final bpm = 60 + random.nextDouble() * 140;
        final call = sixteenths.callAt(
          // Deliberately includes times BEFORE the bar start: a stroke can arrive
          // early and must wrap, not produce a negative crossing.
          onsetTimeSec: (random.nextDouble() - 0.3) * 40,
          barStartSec: random.nextDouble() * 20,
          bpm: bpm,
        );
        expect(call.slot, inInclusiveRange(0, 15));
        expect(call.offsetSlots, inInclusiveRange(-0.5, 0.5));
      }
    });

    test('shifting by a whole bar changes nothing', () {
      final random = math.Random(11);
      for (var trial = 0; trial < 300; trial++) {
        final bpm = 60 + random.nextDouble() * 140;
        final barSec = 4 * 60.0 / bpm;
        final at = random.nextDouble() * 10;
        final bars = random.nextInt(9) - 4;
        final base = sixteenths.callAt(
          onsetTimeSec: at,
          barStartSec: 0,
          bpm: bpm,
        );
        final shifted = sixteenths.callAt(
          onsetTimeSec: at + bars * barSec,
          barStartSec: 0,
          bpm: bpm,
        );
        expect(shifted.slot, base.slot, reason: 'bpm $bpm bars $bars');
        expect(shifted.direction, base.direction);
      }
    });

    test('shifting by one crossing advances it, and flips the arrow', () {
      final random = math.Random(13);
      for (var trial = 0; trial < 300; trial++) {
        final bpm = 60 + random.nextDouble() * 140;
        final slotSec = 4 * 60.0 / bpm / 16;
        final at = random.nextDouble() * 10;
        final base = sixteenths.callAt(
          onsetTimeSec: at,
          barStartSec: 0,
          bpm: bpm,
        );
        final next = sixteenths.callAt(
          onsetTimeSec: at + slotSec,
          barStartSec: 0,
          bpm: bpm,
        );
        expect(next.slot, (base.slot + 1) % 16, reason: 'bpm $bpm');
        // On a strict alternation this is the pendulum itself: consecutive
        // sixteenths must be opposite strokes.
        expect(next.direction, isNot(base.direction));
      }
    });

    test('a displacement under half a crossing keeps the crossing', () {
      // This is the geometric fact the measured timing-scatter row rests on: at
      // 120 bpm a sixteenth is 125 ms, so the channel tolerates +-62.5 ms of
      // learner error before it reads the neighbouring crossing. Measured AUC at
      // +-50 ms scatter is 0.8427, at +-80 ms it falls to 0.6285
      // (`docs/eval/guitarset-strum-baseline.md`) -- the knee sits where this
      // geometry says it should.
      final random = math.Random(17);
      for (var trial = 0; trial < 1000; trial++) {
        final bpm = 60 + random.nextDouble() * 140;
        final slotSec = 4 * 60.0 / bpm / 16;
        final slot = random.nextInt(16);
        final centre = slot / 16 * (4 * 60.0 / bpm);
        // Strictly inside the half-crossing band, so the boundary tie-break
        // (which rounds away from zero) is not what is being asserted here.
        final offset = (random.nextDouble() - 0.5) * 0.98 * slotSec;
        final call = sixteenths.callAt(
          onsetTimeSec: centre + offset,
          barStartSec: 0,
          bpm: bpm,
        );
        expect(call.slot, slot, reason: 'bpm $bpm slot $slot offset $offset');
      }
    });
  });
}
