import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';
import 'package:strumsight/core/music/strum.dart';
import 'package:strumsight/features/live/engine/dsp/strum_metric_channel.dart';

/// The metric channel (ADR 0557/0558). Three groups, matching AGENTS.md §9's
/// demands for a measurement-backed change: PARITY against the fixture the
/// Python probe generated, the STATE contract (the three outcomes must stay
/// distinguishable), and randomized PROPERTIES over the geometry.
void main() {
  group('parity with the measured rule (fixture)', () {
    // If these ever disagree, the shipped rule is not the rule the 0.9797 was
    // measured under, and every number quoted for this channel is void
    // (`docs/LESSONS.md` L662). The fixture is regenerated by
    // `ml/make_metric_channel_fixture.py`.
    final file = File('test/fixtures/strum_metric_channel_parity.json');

    test('fixture exists', () {
      expect(
        file.existsSync(),
        isTrue,
        reason: 'run ml/make_metric_channel_fixture.py',
      );
    });

    test('every case reproduces slot, direction and offset', () {
      final fixture =
          jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
      final cases = (fixture['cases'] as List).cast<Map<String, Object?>>();
      expect(cases, isNotEmpty);

      for (final (index, row) in cases.indexed) {
        final channel = StrumMetricChannel(
          pattern: [
            for (final slot in row['slots'] as List)
              switch (slot) {
                'd' => StrumDirection.down,
                'u' => StrumDirection.up,
                _ => null,
              },
          ],
          beatsPerBar: row['beatsPerBar']! as int,
        );
        // The fixture stores a bar PHASE; turn it back into a time against a
        // fixed tempo so the unit is exercised through its real entry point
        // rather than through an internal shortcut.
        const bpm = 120.0;
        final barSec = channel.beatsPerBar * 60.0 / bpm;
        final phase = (row['phaseInBar']! as num).toDouble();
        final call = channel.callAt(
          onsetTimeSec: 7.5 + phase * barSec,
          barStartSec: 7.5,
          bpm: bpm,
        );
        final where = 'case $index (${row['pattern']}, phase $phase)';
        expect(call.slot, row['expectedSlot'], reason: 'slot, $where');
        expect(call.direction, switch (row['expectedDirection']) {
          'd' => StrumDirection.down,
          'u' => StrumDirection.up,
          _ => null,
        }, reason: 'direction, $where');
        expect(
          call.offsetSlots,
          closeTo((row['expectedOffsetSlots']! as num).toDouble(), 1e-9),
          reason: 'offset, $where',
        );
      }
    });
  });

  group('the three states stay distinguishable', () {
    // Collapsing these is what makes this class dangerous: "no grid" and "the
    // pattern prescribes a rest here" both mean the fusion must fall back to the
    // acoustic channel, but they are different diagnostics and only one of them
    // is a pattern violation worth telling the learner about (ADR 0556 D4).
    const eighths = StrumMetricChannel(
      pattern: [
        StrumDirection.down,
        StrumDirection.up,
        StrumDirection.down,
        StrumDirection.up,
        StrumDirection.down,
        StrumDirection.up,
        StrumDirection.down,
        StrumDirection.up,
      ],
      beatsPerBar: 4,
    );
    const downOnly = StrumMetricChannel(
      pattern: [
        StrumDirection.down,
        null,
        StrumDirection.down,
        null,
        StrumDirection.down,
        null,
        StrumDirection.down,
        null,
      ],
      beatsPerBar: 4,
    );

    test('no tempo grid is UNAVAILABLE, not a guess', () {
      for (final bpm in [0.0, -1.0, double.nan, double.infinity]) {
        final call = eighths.callAt(
          onsetTimeSec: 1.0,
          barStartSec: 0.0,
          bpm: bpm,
        );
        expect(call.available, isFalse, reason: 'bpm $bpm');
        expect(call.hasOpinion, isFalse, reason: 'bpm $bpm');
        expect(call.direction, isNull, reason: 'bpm $bpm');
        expect(call.slot, -1, reason: 'bpm $bpm');
      }
    });

    test('a non-finite time is UNAVAILABLE rather than a wrapped NaN slot', () {
      expect(
        eighths
            .callAt(onsetTimeSec: double.nan, barStartSec: 0, bpm: 120)
            .available,
        isFalse,
      );
      expect(
        eighths
            .callAt(onsetTimeSec: 1, barStartSec: double.infinity, bpm: 120)
            .available,
        isFalse,
      );
    });

    test('a REST slot is available but has NO OPINION', () {
      // 120 bpm, 4/4: a bar is 2 s, an eighth 0.25 s. Slot 1 is the rest.
      final call = downOnly.callAt(
        onsetTimeSec: 0.25,
        barStartSec: 0.0,
        bpm: 120,
      );
      expect(call.slot, 1);
      expect(call.available, isTrue);
      expect(call.hasOpinion, isFalse);
      expect(call.direction, isNull);
    });

    test('a prescribed slot names a direction', () {
      final down = eighths.callAt(
        onsetTimeSec: 0.5,
        barStartSec: 0.0,
        bpm: 120,
      );
      expect(down.slot, 2);
      expect(down.direction, StrumDirection.down);
      expect(down.hasOpinion, isTrue);

      final up = eighths.callAt(onsetTimeSec: 0.75, barStartSec: 0.0, bpm: 120);
      expect(up.slot, 3);
      expect(up.direction, StrumDirection.up);
    });

    test('slotsPerBeat reports the subdivision', () {
      expect(eighths.slotsPerBeat, 2.0);
      const sixteenths = StrumMetricChannel(
        pattern: [
          StrumDirection.down,
          StrumDirection.up,
          StrumDirection.down,
          StrumDirection.up,
        ],
        beatsPerBar: 1,
      );
      expect(sixteenths.slotsPerBeat, 4.0);
    });
  });

  group('properties (randomized)', () {
    // Sixteenth-note alternation over a 4/4 bar: GuitarSet's implied lesson, and
    // the pattern every number in ADR 0557/0558 was measured under.
    final sixteenths = StrumMetricChannel(
      pattern: [
        for (var i = 0; i < 16; i++)
          i.isEven ? StrumDirection.down : StrumDirection.up,
      ],
      beatsPerBar: 4,
    );

    test('an onset dead on a slot centre lands on that slot', () {
      final random = math.Random(20260912);
      for (var trial = 0; trial < 400; trial++) {
        final bpm = 60 + random.nextDouble() * 140; // the TempoTracker's range
        final barStart = random.nextDouble() * 30;
        final slot = random.nextInt(16);
        final barSec = 4 * 60.0 / bpm;
        final call = sixteenths.callAt(
          onsetTimeSec: barStart + slot / 16 * barSec,
          barStartSec: barStart,
          bpm: bpm,
        );
        expect(call.slot, slot, reason: 'bpm $bpm slot $slot');
        expect(call.offsetSlots.abs(), lessThan(1e-9));
        expect(
          call.direction,
          slot.isEven ? StrumDirection.down : StrumDirection.up,
        );
      }
    });

    test('offsetSlots always lies within [-0.5, 0.5]', () {
      final random = math.Random(7);
      for (var trial = 0; trial < 2000; trial++) {
        final bpm = 60 + random.nextDouble() * 140;
        final call = sixteenths.callAt(
          // Deliberately includes times BEFORE the bar start: the pipeline
          // re-anchors bars, so a stroke can arrive early and must wrap, not
          // produce a negative slot.
          onsetTimeSec: (random.nextDouble() - 0.3) * 40,
          barStartSec: random.nextDouble() * 20,
          bpm: bpm,
        );
        expect(call.slot, inInclusiveRange(0, 15));
        expect(call.offsetSlots, inInclusiveRange(-0.5, 0.5));
      }
    });

    test('shifting by a whole bar changes nothing', () {
      final random = math.Random(11);
      for (var trial = 0; trial < 300; trial++) {
        final bpm = 60 + random.nextDouble() * 140;
        final barSec = 4 * 60.0 / bpm;
        final at = random.nextDouble() * 10;
        final bars = random.nextInt(9) - 4;
        final base = sixteenths.callAt(
          onsetTimeSec: at,
          barStartSec: 0,
          bpm: bpm,
        );
        final shifted = sixteenths.callAt(
          onsetTimeSec: at + bars * barSec,
          barStartSec: 0,
          bpm: bpm,
        );
        expect(shifted.slot, base.slot, reason: 'bpm $bpm bars $bars');
        expect(shifted.direction, base.direction);
      }
    });

    test(
      'shifting by one slot advances the slot by one, and flips the arrow',
      () {
        final random = math.Random(13);
        for (var trial = 0; trial < 300; trial++) {
          final bpm = 60 + random.nextDouble() * 140;
          final slotSec = 4 * 60.0 / bpm / 16;
          final at = random.nextDouble() * 10;
          final base = sixteenths.callAt(
            onsetTimeSec: at,
            barStartSec: 0,
            bpm: bpm,
          );
          final next = sixteenths.callAt(
            onsetTimeSec: at + slotSec,
            barStartSec: 0,
            bpm: bpm,
          );
          expect(next.slot, (base.slot + 1) % 16, reason: 'bpm $bpm');
          // On a strict alternation this is the pendulum itself: consecutive
          // sixteenths must be opposite strokes.
          expect(next.direction, isNot(base.direction));
        }
      },
    );

    test('a displacement under half a slot keeps the slot', () {
      // This is the geometric fact the measured timing-scatter row rests on: at
      // 120 bpm a sixteenth is 125 ms, so the channel tolerates +-62.5 ms of
      // learner error before it reads the neighbouring slot. Measured AUC at
      // +-50 ms scatter is 0.8427, at +-80 ms it falls to 0.6285
      // (`docs/eval/guitarset-strum-baseline.md`) -- the knee sits where this
      // geometry says it should.
      final random = math.Random(17);
      for (var trial = 0; trial < 1000; trial++) {
        final bpm = 60 + random.nextDouble() * 140;
        final slotSec = 4 * 60.0 / bpm / 16;
        final slot = random.nextInt(16);
        final centre = slot / 16 * (4 * 60.0 / bpm);
        // Strictly inside the half-slot band, so the boundary tie-break (which
        // rounds away from zero) is not what is being asserted here.
        final offset = (random.nextDouble() - 0.5) * 0.98 * slotSec;
        final call = sixteenths.callAt(
          onsetTimeSec: centre + offset,
          barStartSec: 0,
          bpm: bpm,
        );
        expect(call.slot, slot, reason: 'bpm $bpm slot $slot offset $offset');
      }
    });
  });
}
