/// Public domain contract for cross-feature Audio Analysis consumers.
library;

export 'data/analysis_document_codec.dart';
export 'data/capture/analysis_recorder.dart';
export 'data/capture/recording_run.dart';
export 'data/legacy_analyze_adapter.dart';
export 'data/legacy_view_adapter.dart';
export 'domain/analysis_progress.dart';
export 'domain/preprocessed_audio.dart';
export 'domain/analysis_capability.dart';
export 'domain/analysis_document.dart';
export 'domain/analysis_event.dart';
export 'domain/analysis_hotspot.dart';
export 'domain/analysis_input.dart';
export 'domain/analysis_input_summary.dart';
export 'domain/analysis_insight.dart';
export 'domain/analysis_metric.dart';
export 'domain/analysis_metric_catalog.dart';
export 'domain/analysis_mode.dart';
export 'domain/analysis_provenance.dart';
export 'domain/analysis_segment.dart';
export 'domain/analysis_timeline.dart';
export 'domain/analysis_warning.dart';
export 'domain/recording_level.dart';
export 'domain/signal_quality_report.dart';
export 'engine/analysis_cancellation.dart';
export 'engine/analysis_provenance_builder.dart';
export 'engine/legacy/clip_analyzer_stage.dart';
export 'engine/legacy/legacy_evidence.dart';
export 'engine/quality/quality_thresholds.dart';
export 'engine/quality/signal_quality_stage.dart';
